name: CI Backend

on:
  push:
    branches: [ main ]
    paths: 'backend/**'
  pull_request:
    branches: [ main ]
    paths: 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Scan for secrets with GitLeaks
        uses: github/codeql-action/analyze@v1
        with:
          config-file: config/gitleaks.yml
          languages: javascript